
os: Visual Studio 2015

matrix:
  fast_finish: true

environment:
  matrix:
    # 32-bit MSVC
    - channel: 1.33.0
      target: i686-pc-windows-msvc
    # 64-bit MSVC
    - channel: 1.33.0
      target: x86_64-pc-windows-msvc

install:
  # Put our DLL in place, depending on 32-bit/64-bit
  - if %target%==i686-pc-windows-msvc cp win32-dynamic-link-files\x86\SDL2.dll .
  - if %target%==i686-pc-windows-msvc dir *.dll
  - if %target%==x86_64-pc-windows-msvc cp win32-dynamic-link-files\x64\SDL2.dll .
  - if %target%==x86_64-pc-windows-msvc dir *.dll
  # Setup Rust
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  # dynamic
  - cargo build
  - cargo +nightly test
  - cargo clean
  # static
  - cargo build --no-default-features --features="static_link"
  - cargo +nightly test --no-default-features --features="static_link"
  - cargo clean
