
os: Visual Studio 2017

environment:
  # The pre-built SDL2 files that we have are for MSVC only.
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
      dllpath: lib/msvc-x64-dynamic/SDL2.dll

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - cargo install bindgen
  - rustc -vV
  - cargo -vV

build: false

test_script:
  # We cannot run doctests because rustdoc is silly and tries to interpret too
  # much stuff as code blocks and then dies when the "code blocks" don't contain
  # valid rust. https://github.com/rust-lang/rust/issues/59867 We should still
  # run all the other tests of course.

  # First we verify the pre-generated bindings.
  - cargo build
  - cargo build --examples
  - cargo test --lib --tests

  # Next we attempt with `use_bindgen_bin`
  - cargo clean
  - cargo build --features="use_bindgen_bin"
  - cargo build --features="use_bindgen_bin" --examples
  - cargo test  --features="use_bindgen_bin" --lib --tests

  # Next we attempt with `use_bindgen_lib`
  - cargo clean
  - cargo build --features="use_bindgen_lib"
  - cargo build --features="use_bindgen_lib" --examples
  - cargo test  --features="use_bindgen_lib" --lib --tests
  
  # Next we attempt with `dynamic_link` (using builtin bindings)
  - cargo clean
  - cp %dllpath% .
  - cargo build --features="dynamic_link"
  - cargo build --features="dynamic_link" --examples
  - cargo test  --features="dynamic_link" --lib --tests
